version: "3"

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: localstack-dev
    container_name: app-container
    ports:
      - "80:80"
    networks:
      - my-stack-dev

  localstack:
    image: localstack/localstack
    container_name: localstack-container
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,sqs,sns  # Include additional services as needed
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=your-access-key-id
      - AWS_SECRET_ACCESS_KEY=your-secret-access-key
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - my-stack-dev

networks:
  my-stack-dev:
    driver: bridge
